name: Build and Deploy
on:
  push:
    branches:
      - master # branch to trigger on
env:
  duplo_host: https://qa-govcloud.duplocloud.net
  duplo_token: ${{ secrets.DUPLO_TOKEN }}
  TENANT_NAME:  maja2703 # DuploCloud Tenant name

jobs:
## get AWS credentials, then lists all S3 buckets.
         
  deploy:
    # This example get AWS credentials, then lists all S3 buckets.
    name: using GHA Jit update multiple services
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: duplocloud/ghactions-service-update@master
        with:
          tenant: "${{ env.TENANT_NAME }}"
          services: |-
            [
              { "Name": "serv1", "Image": "nginx:latest" },
              { "Name": "serv2", "Image": "nginx:latest" },
              { "Name": "serv3", "Image": "nginx:latest2" },
              { "Name": "serv4", "Image": "nginx:latest12" },
              { "Name": "serv5", "Image": "nginx:latest12" },
               { "Name": "serv6", "Image": "nginx:latest121" },
              { "Name": "serv7", "Image": "nginx:latest12" },
              { "Name": "serv8", "Image": "nginx:latest12" },
              { "Name": "serv9", "Image": "nginx:latest1233" },
              { "Name": "serv10", "Image": "nginx:latest12" },
               { "Name": "serv11", "Image": "nginx:latest121" },
              { "Name": "serv12", "Image": "nginx:latest12" },
              { "Name": "serv13", "Image": "nginx:latest12" },
              { "Name": "serv14", "Image": "nginx:latest12" },
              { "Name": "serv15", "Image": "nginx:latest12" },
               { "Name": "serv16", "Image": "nginx:latest181" },
              { "Name": "serv17", "Image": "nginx:latest1" },
              { "Name": "serv18", "Image": "nginx:latest12" },
              { "Name": "serv19", "Image": "nginx:latest12" },
              { "Name": "serv20", "Image": "nginx:latest12" }
            ]

