name: Build Image

on:
  workflow_dispatch:
    inputs:
      name:
        description: The name of the service
        required: true
      tags:
        description: The tags to apply to the image
        required: false
  push:
      branches:
        - test-branch
      paths:
        - '.github/workflows/build-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: ${{ vars.DUPLO_HOST }}
      DUPLO_TENANT: ${{ vars.DUPLO_TENANT }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Duplo Setup
      uses: duplocloud/actions@node24-upgrade

    - name: Build and Push Docker Image
      uses: duplocloud/actions/build-image@node24-upgrade
      with:
        repo: my-repo
        registry: my-registry
        platforms: linux/amd64,linux/arm64
        build-args: >
          MY_VAR=value
        context: ./app
        dockerfile: Dockerfile.dev
        push: true
        cache: true
        extra-args: --ssh=default=$SSH_AUTH_SOCK
