name: Build and Deploy
on:
  push:
    branches:
      - master # branch to trigger on
env:
  duplo_host: https://perf.duplocloud.net
  duplo_token: ${{ secrets.DUPLO_TOKEN }}
  TENANT_NAME:  maja0704 # DuploCloud Tenant name

jobs:
## get AWS credentials, then lists all S3 buckets.
         
  deploy:
    # This example get AWS credentials, then lists all S3 buckets.
    name: using GHA Jit update multiple servicesq
    runs-on: ubuntu-latest
    environment: 
      name: perf
    env:
      duplo_host: https://perf.duplocloud.net
      duplo_token: ${{ secrets.DUPLO_TOKEN }}
      TENANT_NAME:  maja0704 # DuploCloud Tenant name
    steps:
      - name: Deploy
        uses: duplocloud/ghactions-service-update@master
        with:
          tenant: "${{ env.TENANT_NAME }}"
          services: |-
            [
              { "Name": "serv1", "Image": "nginx:perl" },
              { "Name": "serv2", "Image": "nginx:perl" },
              { "Name": "serv3", "Image": "nginx:latest2" },
              { "Name": "serv4", "Image": "nginx:latest162" },
              { "Name": "serv5", "Image": "nginx:latest12" },
               { "Name": "serv6", "Image": "nginx:latest16" },
              { "Name": "serv7", "Image": "nginx:latest12" },
              { "Name": "serv8", "Image": "nginx:latest126" },
              { "Name": "serv9", "Image": "nginx:latest133" },
              { "Name": "serv10", "Image": "nginx:latest12" },
               { "Name": "serv11", "Image": "nginx:latest91" },
              { "Name": "serv12", "Image": "nginx:perl" },
              { "Name": "serv13", "Image": "nginx:perl" },
              { "Name": "serv14", "Image": "nginx:perl" },
              { "Name": "serv15", "Image": "nginx:latest12" },
               { "Name": "serv16", "Image": "nginx:latest81" },
              { "Name": "serv17", "Image": "nginx:latest21" },
              { "Name": "serv18", "Image": "nginx:latest12" },
              { "Name": "serv19", "Image": "nginx:latest142" },
              { "Name": "serv20", "Image": "nginx:latest12" }
            ]

