name: GCP Run

on:
  workflow_dispatch:
    inputs:
      service:
        description: Service name
        required: true
      image:
        description: Image name
        required: true
  push:
    branches:
      - node24-jt
    paths:
      - '.github/workflows/gcp-run.yml'

jobs:
  gcp-run:
    runs-on: ubuntu-latest
    environment: qa-gcp
    env:
      DUPLO_TOKEN: ${{ secrets.GCP_DUPLO_TOKEN }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      DUPLO_HOST: https://qa-gcp.duplocloud.net
      DUPLO_TENANT: auto-02
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Duplo Setup GCP
        uses: duplocloud/actions@v0.0.14
        with:
          region: us-central1
          account-id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Verify gcloud
        run: |
          gcloud version
          gcloud auth list

      - name: Update Service
        uses: duplocloud/actions/update-service@v0.0.14
        with:
          service: ${{ inputs.service }}
          image: ${{ inputs.image }}
