name: Setup Terraform

on:
  workflow_dispatch:
    inputs:
      name:
        description: The name of the service
        required: true
      tags:
        description: The tags to apply to the image
        required: false
  push:
      branches:
        - test-branch
      paths:
        - '.github/workflows/setup-terraform.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2

    - name: Install TF Dependencies
      uses: duplocloud/actions/setup-terraform@v0.0.14
      with:
        tf_cache_dir: ~/.terraform.d/plugin-cache
        tflint_cache_dir: ~/.tflint.d/plugins
        tflint_version: v0.44.1
        terraform_version: 1.6.1
