name: Setup Terraform

on:
  workflow_dispatch:
    inputs:
      name:
        description: The name of the service
        required: true
      tags:
        description: The tags to apply to the image
        required: false
  push:
      branches:
        - test-branch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Install TF Dependencies
      uses: duplocloud/actions/setup-terraform@node24-upgrade
      with:
        tf_cache_dir: ~/.terraform.d/plugin-cache
        tflint_cache_dir: ~/.tflint.d/plugins
        tflint_version: v0.44.1
        terraform_version: 1.6.1
    - name: Verify Node24
      run: node --version
