name: Update Service using update-image
on:
  workflow_dispatch:
    inputs:
      name:
        description: The name of the service
        required: true
      tags:
        description: The tags to apply to the image
        required: false
  push:
      paths:
        - '.github/workflows/updateservices.yml'
  

jobs:
  update_service:
    name: Update Service
    runs-on: ubuntu-latest
    environment: 
      name: qa-gcp-newinstall
    env:
      DUPLO_TOKEN: ${{ secrets.GCP_DUPLO_TOKEN }}
      DUPLO_HOST: https://qa-gcp-newinstall.duplocloud.net
      DUPLO_TENANT: ar30
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions@main
      with:
        version: latest

    - name: Install duploctl from main
      run: pip install git+https://github.com/duplocloud/duploctl.git@main

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-image@main
      with:
        name: serv3
        image: nginx:1.26
        type: service

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Update Multiple Images
      uses: duplocloud/actions/update-images@main
      with:
        services: |
          [
             
            {
              "service": "serv1",
              "image": "nginx:perl"
            },
              {
              "service": "serv2",
              "image": "nginx:perl"
            },
              {
              "service": "serv3",
              "image": "nginx:perl"
            },
               {
              "service": "serv4",
              "image": "nginx:1.27.5"
            },
              {
              "service": "serv5",
              "image": "nginx:1.27.2"
            }
            
          
          ]

  

        
