name: Update Service using update-image
on:
  workflow_dispatch:
    inputs:
      name:
        description: The name of the service
        required: true
      tags:
        description: The tags to apply to the image
        required: false
  push:
      paths:
        - '.github/workflows/updateservices.yml'
  

jobs:
  update_service:
    name: Update Service
    runs-on: ubuntu-latest
    environment: 
      name: uat-aws
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: https://uat-aws.duplocloud.net
      DUPLO_TENANT: ar29
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions@main
      with:
        version: latest

    - name: Install duploctl from main
      run: pip install git+https://github.com/duplocloud/duploctl.git@main

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-image@main
      with:
        name: serv3
        image: nginx:123
        type: service

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2     

    - name: Update Multiple Images
      uses: duplocloud/actions/update-images@main
      with:
        services: |
          [
             
            {
              "service": "serv3",
              "image": "nginx:perl"
            },
              {
              "service": "serv2",
              "image": "nginx:perl"
            },
              {
              "service": "serv3",
              "image": "nginx:perl"
            },
               {
              "service": "serv4",
              "image": "nginx:1.27.5"
            },
              {
              "service": "serv5",
              "image": "nginx:1.27.2"
            }
            
          
          ]

  

        
