name: Build and Deploy
on:
  push:
    branches:
      - master # branch to trigger on
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: environment
        default: qaperf-1-80
        required: true
      image:
        description: The full image
        type: string
        required: true
env:
  duplo_host: https://perf.duplocloud.net
  duplo_token: ${{ secrets.DUPLO_TOKEN }}
  TENANT_NAME: qaperf-1-80	# DuploCloud Tenant name
jobs:
  update_service:
    name: Update Service
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    env:
      DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}
      DUPLO_HOST: https://perf.duplocloud.net
      DUPLO_TENANT: qaperf-1-80	
    steps: 
    
    # install and login to the cloud
    - name: Duplo Setup
      uses: duplocloud/actions@v0.0.13

    # uses duploctl from above
    - name: Update Service
      uses: duplocloud/actions/update-image@v0.0.5
      with:
        name: my-service
        image: nginx:123
        type: service
